name: dogfood-msinternal (prod)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4.2.0
        with:
          node-version: latest
      - run: |
          node launch.js > launch.sh
          sh launch.sh

      - uses: actions/upload-artifact@v4.6.1
        with:
          path: Production_CC_*_x64_O365ProPlusRetail_en-us.zip
